---
sudo: required
# docker is required to run tests
services: docker

install:
  - bundle install

script:
  # run kitchen tests (destroy, create, converge, setup, verify and destroy)
  - bundle exec kitchen test

notifications:
  slack:
    secure: K+Qf40Tui8xo71/0m6v6B+LYl8eTfiBYUu5u8+amGNIERtfbhtvzuYhIYBZGaa1cWJeQc8woAbdDvh4vh/Lj22TR3PsNG3UGgb75lSrYpJ9XJOiuBeyP35nXF1lhCOzFVhwziMdQWy1nfvl16dTIb73G/tFCZMotu9Jl2bZDl2G88bkFZlLtuX3rEXbmyqNIYiy3Z3f+3N5hujenBOABGblnui63vjROy4slM991UbdX++c/ogg+czzopl7C3zAqCPj4fqp7Wu5S0jwn15IFy1dgnJzVqlmvrpwxkzl7K3K9lvRnG/dk0louNlaUiIinzZ3npUqOPkY66e7SoiFhgjeXRHK/33it0UriifPcw1+f9ZvbzyULlYmvvIRAOyQyKikLC/SP4Q4X/Y55KdKmE8wB54q8bRKwSjlTtkDCLBmYiAApV58uyL1hyqHee7wQkYzLHZ1IkE35/mrBxDCoy8QrmCQBmdJv2H+dQVc8VhTWVSOMo+FLHr0d7jp/Kmngvo/OJYbAwPPQbl7vjOSHlLkbf9tqFRGsMzZsiqeTrRxWe4FVB599gA7h7KJ3CAzSsgtpugd+m9mk6/GBoYooouBDkxx4qD6LSMLjhYerYYCgHQCX5s1p9+A1cXtZ3T6DSUncQ7Hx0Q+beLWS8MOmFdqBNVt5K2CND5fdwiOBLqo=
